import { IProduct } from 'app/types/product';

export const productsDB: IProduct[] = [
  //   {
  //     id: 'QQ3y-Z40iYX8u1Uor2fkn',
  //     url: '/public/img/SKINATON.webp',
  //     name: 'Zara',
  //     sizeType: 'объём',
  //     size: '10',
  //     barcode: '1234567890',
  //     manufacturer: 'Испания',
  //     brand: 'Zara',
  //     description: 'Парфюмерная вода',
  //     price: '469',
  //     typeOfCare: ['подарочные наборы', ' гигиеническая продукция'],
  //     cosmeticType: true,
  //   },
  {
    id: 'YF78STa5WyUCZLELJd9Js',
    url: 'https://ir.ozone.ru/s3/multimedia-1/wc1000/6265230073.jpg',
    name: 'Skinaton',
    sizeType: 'объём',
    size: '50',
    barcode: '1234567890',
    manufacturer: 'Россия',
    brand: ' SKINATON',
    description:
      'Средство от прыщей на лице / лосьон для умывания для проблемной кожи/ очищающее средство для умывания от прыщей и против акне/ чистая кожа лица',
    price: '1500',
    typeOfCare: ['уход за лицом'],
    cosmeticType: true,
  },
  {
    id: 'YF78STa5WyUCZLELJd9Js',
    url: 'https://ir.ozone.ru/s3/multimedia-1/wc1000/6265230073.jpg',
    name: 'Skinaton',
    sizeType: 'объём',
    size: '50',
    barcode: '1234567890',
    manufacturer: 'Россия',
    brand: ' SKINATON',
    description:
      'Средство от прыщей на лице / лосьон для умывания для проблемной кожи/ очищающее средство для умывания от прыщей и против акне/ чистая кожа лица',
    price: '1500',
    typeOfCare: ['уход за лицом'],
    cosmeticType: true,
  },
  {
    id: 'YF78STa5WyUCZLELJd9Js',
    url: 'https://ir.ozone.ru/s3/multimedia-1/wc1000/6265230073.jpg',
    name: 'Skinaton',
    sizeType: 'объём',
    size: '50',
    barcode: '1234567890',
    manufacturer: 'Россия',
    brand: ' SKINATON',
    description:
      'Средство от прыщей на лице / лосьон для умывания для проблемной кожи/ очищающее средство для умывания от прыщей и против акне/ чистая кожа лица',
    price: '1500',
    typeOfCare: ['уход за лицом'],
    cosmeticType: true,
  },
];
